.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HYPE" "1" "January 2015" "" ""
.
.SH "NAME"
\fBhype\fR \- scriptable, asynchronous network packet generator/analyzer
.
.SH "SYNOPSIS"
\fBhype <targets> [options]\fR
.
.SH "DESCRIPTION"
\fBhype\fR is a command\-line packet generator and analyzer\. It lets you generate custom IP/ICMP/TCP/UDP packets, send them over the network and analyze replies using Lua scripts\.
.
.SH "OPTIONS"
\fB\-S, \-\-script=<file>\fR
.
.P
\~\~\~\~\~\~ Load and run the given script\.
.
.P
\fB\-p, \-\-ports=<ranges>\fR
.
.P
\~\~\~\~\~\~ Use the specified port ranges\.
.
.P
\fB\-r, \-\-rate=<packets_per_second>\fR
.
.P
\~\~\~\~\~\~ Send packets no faster than the specified rate (default is 100)\.
.
.P
\fB\-s, \-\-seed=<seed>\fR
.
.P
\~\~\~\~\~\~ Use the given number as seed value\.
.
.P
\fB\-w, \-\-wait=<seconds>\fR
.
.P
\~\~\~\~\~\~ Wait the given amount of seconds after the scan is complete (default is 5)\.
.
.P
\fB\-c, \-\-count=<count>\fR
.
.P
\~\~\~\~\~\~ Send the given amount of duplicate packets (default is 1)\.
.
.P
\fB\-q, \-\-quiet\fR
.
.P
\~\~\~\~\~\~ Don\'t show the status line\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2015 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
